version: 2
jobs:
  build-test-and-docs:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run PyTest
          command: |
            poetry run pytest
      - run:
          name: Run flake8 style checker
          command: |
            poetry run flake8 .
      - run:
          name: Build docs
          command: |
            cd docs/
            poetry run make clean
            poetry run make html
      - persist_to_workspace:
          root: docs/build
          paths:
            - html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/build
      - run:
          name: Disable Jekyll builds
          command: touch docs/build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "cbryant@berkeley.edu"
            git config user.name "chrismbryant"
      - add_ssh_keys:
          fingerprints:
            - "ce:32:46:37:4d:b2:dd:d6:54:cf:36:38:41:11:f9:98"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html

workflows:
  version: 2
  main-workflow:
    jobs:
      - build-test-and-docs
      - docs-deploy:
          requires:
            - build-test-and-docs
          filters:
            branches:
              only: main